export const MOCK_GUESTS = [
    {
        id: '1',
        name: 'Carlos Mendez',
        guestCount: 2,
        confirmed: true,
        confirmDate: '2025-05-10',
        group: 'Familia',
        active: true,
    },
    {
        id: '2',
        name: 'Ana Rodriguez',
        guestCount: 1,
        confirmed: false,
        confirmDate: null,
        group: 'Amigos',
        active: true,
    },
    {
        id: '3',
        name: 'Luis Garcia',
        guestCount: 3,
        confirmed: true,
        confirmDate: '2025-05-15',
        group: 'Trabajo',
        active: true,
    },
    {
        id: '4',
        name: 'Sofia Martinez',
        guestCount: 2,
        confirmed: false,
        confirmDate: null,
        group: 'Amigos',
        active: true,
    },
    {
        id: '5',
        name: 'Miguel Torres',
        guestCount: 1,
        confirmed: true,
        confirmDate: '2025-05-12',
        group: 'Familia',
        active: true,
    },
]